# Generated by Django 4.0.4 on 2022-05-31 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtatTicket',
            fields=[
                ('idEtatTicket', models.IntegerField(primary_key=True, serialize=False)),
                ('intituleEtatTicket', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('idTicket', models.AutoField(primary_key=True, serialize=False)),
                ('intituleTicket', models.CharField(max_length=255)),
                ('descriptionTicket', models.TextField()),
                ('dateLimitTicket', models.DateTimeField()),
                ('donneesTicket', models.CharField(max_length=255, null=True)),
                ('remarquesTicket', models.TextField(null=True)),
                ('assistante', models.CharField(max_length=255, null=True)),
                ('file', models.FileField(null=True, upload_to='tickets')),
                ('etatTicket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticketsManagement.etatticket')),
            ],
        ),
    ]
